version: "3"
services:
  fluido:
    build:
      context: fluido
      dockerfile: Dockerfile

    volumes:
      - ./fluido/src:/app/src
      - ./fluido/public:/app/public
      - ./fluido/package.json:/app/package.json
      - ./fluido/build:/app/build
    env_file:
      - ./fluido/.env
    ports:
      - "3000:3000"
